services:
  db:
    image: 'postgres:16-alpine'
    environment:
      - POSTGRES_NAME=abraao
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: ["postgres", "-c", "max_locks_per_transaction=1024"]
  web:
    build: .
    volumes:
      - '.:/home/dev/code'
      - '/home/italo/.ssh:/home/dev/.ssh'
      - '/tmp/.X11-unix/:/tmp/.X11-unix/'
    environment:
      - POSTGRES_NAME=abraao
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DISPLAY=$DISPLAY
    depends_on:
      - db
    ports:
      - '8001:8001'
    stdin_open: true
    tty: true