services:
  db_mysql:
    image: mysql:8.0
    env_file:
      - .env
    restart: always
  web:
    image: ghcr.io/italo2sanfer/abraao:1.0
    restart: always
    env_file:
      - .env
    depends_on:
      - db_mysql
    ports:
      - '8002:${APP_PORT}'
    stdin_open: true
    tty: true