# Generated by Django 4.2 on 2025-11-04 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=70, unique=True, verbose_name='Code')),
                ('passwd', models.CharField(max_length=70, unique=True, verbose_name='Passwd')),
                ('description', models.CharField(max_length=500, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('description', models.CharField(max_length=500, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(choices=[(1, 'Italo'), (2, 'Vivia'), (3, 'Télia'), (4, 'Valdir'), (4, 'Penha')], max_length=50, verbose_name='Who')),
                ('login', models.CharField(max_length=70, verbose_name='Login')),
                ('access', models.CharField(max_length=500, verbose_name='Name')),
                ('description', models.CharField(max_length=500, verbose_name='Name')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passapp.service', verbose_name='Service')),
            ],
        ),
    ]
