# Generated by Django 4.2 on 2025-11-17 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=70, unique=True, verbose_name='Code')),
                ('passwd', models.CharField(blank=True, max_length=70, verbose_name='Passwd')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Paty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('url', models.CharField(blank=True, max_length=100, verbose_name='URL')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Joao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(choices=[('Italo', 'Italo'), ('Vivia', 'Vivia'), ('Angelica', 'Angelica'), ('Telia', 'Télia'), ('Valdir', 'Valdir'), ('Penha', 'Penha')], max_length=50, verbose_name='Who')),
                ('login', models.CharField(max_length=70, verbose_name='Login')),
                ('access', models.CharField(max_length=500, verbose_name='Access')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('paty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passapp.paty', verbose_name='Paty')),
            ],
        ),
    ]
