# Generated by Django 4.2 on 2025-11-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='access',
            field=models.CharField(max_length=500, verbose_name='Access'),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='password',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='password',
            name='passwd',
            field=models.CharField(max_length=70, verbose_name='Passwd'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
    ]
