# Generated by Django 4.2 on 2025-11-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passapp', '0002_alter_account_access_alter_account_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
