# Generated by Django 4.2 on 2025-11-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passapp', '0003_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='account',
            name='who',
            field=models.CharField(choices=[('Italo', 'Italo'), ('Vivia', 'Vivia'), ('Angelica', 'Angelica'), ('Telia', 'Télia'), ('Valdir', 'Valdir'), ('Penha', 'Penha')], max_length=50, verbose_name='Who'),
        ),
        migrations.AlterField(
            model_name='password',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='password',
            name='passwd',
            field=models.CharField(blank=True, max_length=70, verbose_name='Passwd'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.CharField(blank=True, max_length=100, verbose_name='URL'),
        ),
    ]
