# Generated by Django 4.2 on 2026-04-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moises", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joao",
            name="who",
            field=models.CharField(
                choices=[
                    ("Italo", "Italo"),
                    ("Vivia", "Vivia"),
                    ("Angelica", "Angelica"),
                    ("Telia", "Télia"),
                    ("Valdir", "Valdir"),
                    ("Penha", "Penha"),
                    ("IFF", "IFF"),
                ],
                max_length=50,
                verbose_name="Who",
            ),
        ),
        migrations.AlterField(
            model_name="judite",
            name="passwd",
            field=models.CharField(max_length=300, unique=True, verbose_name="Passwd"),
        ),
    ]
