# Generated by Django 4.2 on 2026-08-30 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moises", "0002_alter_joao_who_alter_judite_passwd"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="joao",
            name="who",
        ),
        migrations.CreateModel(
            name="Davi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("Own", "Own")],
                        max_length=50,
                        verbose_name="Role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="joao",
            name="davi",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="moises.davi",
                verbose_name="Davi",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="joao",
            name="group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="moises.group",
                verbose_name="Group",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="judite",
            name="davi",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="moises.davi",
                verbose_name="Davi",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paty",
            name="davi",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="moises.davi",
                verbose_name="Davi",
            ),
            preserve_default=False,
        ),
    ]
