# Generated by Django 4.2 on 2026-08-30 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("moises", "0003_group_remove_joao_who_davi_joao_davi_joao_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="davi",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="moises.davi",
                verbose_name="Davi",
            ),
            preserve_default=False,
        ),
    ]
