# Generated by Django 4.2 on 2026-09-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moises", "0004_group_davi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="judite",
            name="code",
            field=models.CharField(max_length=70, verbose_name="Code"),
        ),
    ]
